Repository resqiar/dikenang, pull requests merged in 2021-05, with the labels that each got.

#31 Fix Incomplete Test Module
  src/auth/auth.resolver.spec.ts
  src/auth/auth.service.spec.ts
  src/users/users.resolver.spec.ts
  src/users/users.service.spec.ts
Labels: Fix, enhancement

#32 Add first documentation patch
  README.md
Labels: documentation

#37 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#40 refactor(global): move server-code to dikser directory
  .github/workflows/CI.yml
  .github/workflows/dikser_test.yml
  .gitignore
  .vscode/settings.json
  dikser/.gitignore
  dikser/nest-cli.json
  dikser/package.json
  dikser/sample.env.txt
  dikser/src/app.module.ts
  dikser/src/auth/auth.module.ts
  dikser/src/auth/auth.resolver.spec.ts
  dikser/src/auth/auth.resolver.ts
  dikser/src/auth/auth.service.spec.ts
  dikser/src/auth/auth.service.ts
  dikser/src/auth/dto/login-input.dto.ts
  dikser/src/auth/guards/gql-jwt.guard.ts
  dikser/src/auth/strategies/jwt.strategy.ts
  dikser/src/database/config/ormconfig.ts
  dikser/src/database/database.module.ts
  dikser/src/main.ts
  dikser/src/posts/dto/create-attachments.input.ts
  dikser/src/posts/dto/create-post.input.ts
  dikser/src/posts/dto/delete-response.dto.ts
  dikser/src/posts/dto/update-post.input.ts
  dikser/src/posts/entities/attachments.entity.ts
  dikser/src/posts/entities/post.entity.ts
  dikser/src/posts/posts.module.ts
  dikser/src/posts/posts.resolver.spec.ts
  dikser/src/posts/posts.resolver.ts
  dikser/src/posts/posts.service.spec.ts
  dikser/src/posts/posts.service.ts
  dikser/src/schema.gql
  dikser/src/shared/decorators/current-user.decorator.ts
  dikser/src/subscribers/users.subscriber.ts
  dikser/src/users/dto/create-user.input.ts
  dikser/src/users/dto/update-user.input.ts
  dikser/src/users/entities/user.entity.ts
  dikser/src/users/users.module.ts
  dikser/src/users/users.resolver.spec.ts
  dikser/src/users/users.resolver.ts
  dikser/src/users/users.service.spec.ts
  dikser/src/users/users.service.ts
  dikser/test/app.e2e-spec.ts
  dikser/test/jest-e2e.json
  dikser/tsconfig.build.json
  dikser/tsconfig.json
  dikser/yarn.lock
Labels: refactor

#39 fix(docs): better grammar, words phrase, capital-case, and punctuation.
  README.md
Labels: documentation

#47 Dockerize dikenang server (dikser)
  README.md
  dikser/.dockerignore
  dikser/Dockerfile
  dikser/README.md
  docker-compose.yml
Labels: documentation, enhancement

#58 Refactor components to use styled-components instead of CSS module
  dikweb/.babelrc
  dikweb/components/body/IndexBody.tsx
  dikweb/components/body/index/IndexBody.module.css
  dikweb/components/body/index/IndexBody.tsx
  dikweb/components/header/Header.module.css
  dikweb/components/header/Header.tsx
  dikweb/components/icons/Icons.module.css
  dikweb/components/icons/Icons.tsx
  dikweb/components/input/Input.module.css
  dikweb/components/input/Input.tsx
  dikweb/components/logo/DikenangLogo.module.css
  dikweb/components/logo/DikenangLogo.tsx
  dikweb/components/sidebar/container/SidebarCard.module.css
  dikweb/components/sidebar/container/SidebarCard.tsx
  dikweb/components/sidebar/leftbar/Leftbar.module.css
  dikweb/components/sidebar/leftbar/Leftbar.tsx
  dikweb/components/sidebar/rightbar/Rightbar.module.css
  dikweb/components/sidebar/rightbar/Rightbar.tsx
  dikweb/package.json
  dikweb/pages/index.tsx
  yarn.lock
Labels: dikweb, enhancement, refactor
